displayName=RuneRadar
author=jcooler
description=Your personal OSRS map with local live location, search and account details
tags=map,location,search,second monitor
version=1.0.0
plugins=com.runeradar.RuneRadarPlugin
build=gradle
