/**
 * RuneRadar — Transport Network Data
 * Fairy rings, spirit trees, teleport locations
 */

const FAIRY_RINGS = [
  { code: "AIQ", name: "Mudskipper Point", x: 2996, y: 3114 },
  { code: "AIR", name: "South of Yanille", x: 2700, y: 3247 },
  { code: "AIS", name: "Auburn Valley (Varlamore)", x: 1430, y: 3323 },
  { code: "AJR", name: "Slayer Cave", x: 2780, y: 3613 },
  { code: "AJS", name: "Penguins", x: 2500, y: 3896 },
  { code: "AKQ", name: "Piscatoris Hunter Area", x: 2319, y: 3619 },
  { code: "AKS", name: "Feldip Hunter Area", x: 2571, y: 2956 },
  { code: "ALP", name: "Lighthouse", x: 2503, y: 3636 },
  { code: "ALQ", name: "Haunted Woods", x: 3597, y: 3495 },
  { code: "ALR", name: "Abyssal Area", x: 3059, y: 4875 },
  { code: "ALS", name: "Sire / McGrubor's Wood", x: 2644, y: 3495 },
  { code: "BIP", name: "SW of Mort Myre", x: 3410, y: 3324 },
  { code: "BIQ", name: "Kalphite Lair", x: 3251, y: 3095 },
  { code: "BIS", name: "Ardougne Zoo", x: 2635, y: 3266 },
  { code: "BJR", name: "Realm of the Fisher King", x: 2650, y: 4730 },
  { code: "BJS", name: "Island near Zul-Andra", x: 2150, y: 3070 },
  { code: "BKP", name: "South of Castle Wars", x: 2385, y: 3035 },
  { code: "BKQ", name: "Enchanted Valley", x: 3041, y: 4532 },
  { code: "BKR", name: "Mort Myre Swamp", x: 3469, y: 3431 },
  { code: "BLP", name: "TzHaar area", x: 2437, y: 5126 },
  { code: "BLR", name: "Legends' Guild", x: 2740, y: 3351 },
  { code: "CIP", name: "Miscellania", x: 2513, y: 3884 },
  { code: "CIQ", name: "NW of Yanille", x: 2528, y: 3127 },
  { code: "CIR", name: "South of Mount Karuulm", x: 1302, y: 3762 },
  { code: "CIS", name: "North of Arceuus Library", x: 1639, y: 3868 },
  { code: "CJR", name: "Sinclair Mansion", x: 2705, y: 3576 },
  { code: "CKR", name: "South of Tai Bwo Wannai", x: 2801, y: 3003 },
  { code: "CKS", name: "Canifis", x: 3447, y: 3470 },
  { code: "CLP", name: "Draynor Island", x: 3082, y: 3206 },
  { code: "CLR", name: "Ape Atoll", x: 2740, y: 2738 },
  { code: "CLS", name: "Hazelmere", x: 2682, y: 3081 },
  { code: "DIP", name: "Abyssal Nexus", x: 3037, y: 4763 },
  { code: "DIR", name: "Gorak's Plane", x: 3038, y: 5348 },
  { code: "DIS", name: "Wizards' Tower", x: 3108, y: 3149 },
  { code: "DJP", name: "Tower of Life", x: 2658, y: 3230 },
  { code: "DJR", name: "Chasm of Fire", x: 1455, y: 3658 },
  { code: "DKP", name: "South of Musa Point", x: 2900, y: 3111 },
  { code: "DKR", name: "Edgeville", x: 3129, y: 3496 },
  { code: "DKS", name: "Snowy Hunter Area", x: 2744, y: 3719 },
  { code: "DLQ", name: "North of Nardah", x: 3423, y: 3016 },
  { code: "DLR", name: "Poison Waste", x: 2213, y: 3099 },
  { code: "DLS", name: "Myreque Hideout", x: 3447, y: 9824 },
  // Added from wiki — missing fairy rings
  { code: "AJP", name: "Varlamore (near Fortis)", x: 1651, y: 3010 },
  { code: "AJQ", name: "Dorgesh-Kaan south dungeon", x: 2735, y: 5221 },
  { code: "AKP", name: "Necropolis", x: 3284, y: 2705 },
  { code: "AKR", name: "Hosidius south", x: 1827, y: 3538 },
  { code: "BJP", name: "Isle of Souls", x: 2267, y: 2976 },
  { code: "BKS", name: "Zanaris", x: 2412, y: 4434 },
  { code: "BLQ", name: "Yu'biusk", x: 3573, y: 4371 },
  { code: "BLS", name: "West of Battlefront", x: 1295, y: 3493 },
  { code: "CJQ", name: "The Great Conch", x: 3178, y: 2447 },
  { code: "CKP", name: "Cosmic Entity's Plane", x: 2075, y: 4848 },
  { code: "CKQ", name: "Varlamore (Aldarin)", x: 1359, y: 2941 },
  { code: "DLP", name: "Grimstone", x: 2923, y: 10454 },
];

const SPIRIT_TREES = [
  { name: "Tree Gnome Village", x: 2539, y: 3166 },
  { name: "Gnome Stronghold", x: 2460, y: 3446 },
  { name: "Battlefield of Khazard", x: 2555, y: 3259 },
  { name: "Grand Exchange", x: 3185, y: 3510 },
  { name: "Brimhaven", x: 2802, y: 3203 },
  { name: "Hosidius", x: 1693, y: 3542 },
  { name: "Farming Guild", x: 1253, y: 3750 },
  { name: "Port Sarim", x: 3060, y: 3258 },
  { name: "Etceteria", x: 2613, y: 3858 },
  { name: "Feldip Hills", x: 2486, y: 2850 },
  { name: "Poison Waste", x: 2339, y: 3111 },
  { name: "Prifddinas", x: 3275, y: 6124 },
  { name: "Laguna Aurorae", x: 1202, y: 2786 },
  { name: "POH (if planted)", x: 0, y: 0 }, // skip, player-specific
];

const WIKI_IMG = "https://oldschool.runescape.wiki/images";

const TELEPORT_LOCATIONS = [
  // Standard spellbook
  { name: "Varrock Teleport", x: 3213, y: 3424, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Lumbridge Teleport", x: 3222, y: 3218, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Falador Teleport", x: 2965, y: 3379, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Camelot Teleport", x: 2757, y: 3478, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Ardougne Teleport", x: 2662, y: 3305, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Watchtower Teleport", x: 2549, y: 3112, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Trollheim Teleport", x: 2891, y: 3676, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },
  { name: "Kourend Castle Teleport", x: 1644, y: 3673, book: "Standard", icon: `${WIKI_IMG}/Law_rune.png` },

  // Ancient spellbook
  { name: "Paddewwa (Edgeville Dungeon)", x: 3098, y: 9882, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Senntisten (Digsite)", x: 3322, y: 3336, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Kharyrll (Canifis)", x: 3492, y: 3471, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Lassar (Ice Mountain)", x: 3003, y: 3470, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Dareeyak (Wilderness)", x: 2966, y: 3696, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Carrallangar (Graveyard)", x: 3156, y: 3666, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Annakarl (Demonic Ruins)", x: 3288, y: 3886, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },
  { name: "Ghorrock (Frozen Waste)", x: 2977, y: 3873, book: "Ancient", icon: `${WIKI_IMG}/Ancient_staff.png` },

  // Lunar spellbook
  { name: "Moonclan Teleport", x: 2111, y: 3916, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Ourania Teleport", x: 2468, y: 3247, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Waterbirth Teleport", x: 2546, y: 3757, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Barbarian Teleport", x: 2544, y: 3569, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Khazard Teleport", x: 2636, y: 3167, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Fishing Guild Teleport", x: 2612, y: 3391, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Catherby Teleport", x: 2802, y: 3449, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },
  { name: "Ice Plateau Teleport", x: 2973, y: 3939, book: "Lunar", icon: `${WIKI_IMG}/Lunar_staff.png` },

  // Jewelry teleports
  { name: "Ring of Dueling → Duel Arena", x: 3315, y: 3235, book: "Jewelry", icon: `${WIKI_IMG}/Ring_of_dueling.png` },
  { name: "Ring of Dueling → Castle Wars", x: 2440, y: 3090, book: "Jewelry", icon: `${WIKI_IMG}/Ring_of_dueling.png` },
  { name: "Ring of Dueling → Ferox Enclave", x: 3150, y: 3635, book: "Jewelry", icon: `${WIKI_IMG}/Ring_of_dueling.png` },
  { name: "Games Necklace → Wintertodt", x: 1623, y: 3938, book: "Jewelry", icon: `${WIKI_IMG}/Games_necklace.png` },
  { name: "Games Necklace → Barbarian Assault", x: 2520, y: 3571, book: "Jewelry", icon: `${WIKI_IMG}/Games_necklace.png` },
  { name: "Games Necklace → Tithe Farm", x: 1794, y: 3500, book: "Jewelry", icon: `${WIKI_IMG}/Games_necklace.png` },
  { name: "Glory → Edgeville", x: 3087, y: 3496, book: "Jewelry", icon: `${WIKI_IMG}/Amulet_of_glory.png` },
  { name: "Glory → Karamja", x: 2918, y: 3176, book: "Jewelry", icon: `${WIKI_IMG}/Amulet_of_glory.png` },
  { name: "Glory → Draynor Village", x: 3105, y: 3249, book: "Jewelry", icon: `${WIKI_IMG}/Amulet_of_glory.png` },
  { name: "Glory → Al Kharid", x: 3293, y: 3163, book: "Jewelry", icon: `${WIKI_IMG}/Amulet_of_glory.png` },
  { name: "Wealth → Grand Exchange", x: 3164, y: 3461, book: "Jewelry", icon: `${WIKI_IMG}/Ring_of_wealth.png` },
  { name: "Wealth → Falador", x: 2996, y: 3375, book: "Jewelry", icon: `${WIKI_IMG}/Ring_of_wealth.png` },
  { name: "Combat Bracelet → Warriors' Guild", x: 2882, y: 3548, book: "Jewelry", icon: `${WIKI_IMG}/Combat_bracelet.png` },
  { name: "Combat Bracelet → Champions' Guild", x: 3191, y: 3367, book: "Jewelry", icon: `${WIKI_IMG}/Combat_bracelet.png` },
  { name: "Combat Bracelet → Monastery", x: 3053, y: 3486, book: "Jewelry", icon: `${WIKI_IMG}/Combat_bracelet.png` },
  { name: "Combat Bracelet → Ranging Guild", x: 2656, y: 3442, book: "Jewelry", icon: `${WIKI_IMG}/Combat_bracelet.png` },
  { name: "Skills Necklace → Fishing Guild", x: 2612, y: 3391, book: "Jewelry", icon: `${WIKI_IMG}/Skills_necklace.png` },
  { name: "Skills Necklace → Mining Guild", x: 3050, y: 9764, book: "Jewelry", icon: `${WIKI_IMG}/Skills_necklace.png` },
  { name: "Skills Necklace → Farming Guild", x: 1249, y: 3719, book: "Jewelry", icon: `${WIKI_IMG}/Skills_necklace.png` },
  { name: "Skills Necklace → Woodcutting Guild", x: 1663, y: 3507, book: "Jewelry", icon: `${WIKI_IMG}/Skills_necklace.png` },
];
